# number = ['1','2','three','4']
# sum = 0
# for n in number:
#     try:
#         sum += int(n)
#     except ValueError:
#         print("エラー要素:"+ n)
# print(sum)

# try:
#     print(10/5)
# except:
#     print('exception')
# else:
#     print("exceptionなし")
# finally:
#     print("finally")